### ISSUE TITLE
Rain Gauge

### ISSUE THREAD

**Issue by ukstorm** [planetk/homebridge-netatmo#1]
Any plans to support the Rain gauge and upcoming Wind gauge?

**Comment by planetk** [comment]
I’d love to add the support. Unfortunately I don’t own this devices, but I can try to add this support tomorrow.
Maybe you could do some testing than?

**Comment by planetk** [comment]
Ok, I did a quick try for the rain sensor. It would be great, if you could test it, before I publish it at npm.

**Comment by ukstorm** [comment]
The good news is it's showing up, just got to wait for some rain :-) The home app shows the battery level as the primary reading, eve did too, but you can edit eve.
Will let you know if it changes from 0 when it rains!
Thank you!

**Comment by planetk** [comment]
Ok, I did add some additional characteristics for the 1 hour and 24 hour sum of the rain. I also added the wind sensor. Again untested...
Unfortunatually I don't know about a way to define an order in the characteristics, but possibly in a future release I'll add some way to exclude services/characteristics via configuration.

**Comment by ukstorm** [comment]
Latest version installed, all 3 values show up :-) just need some rain now. As for the order I think it just how homekit sees it, but thankfully in eve you can edit the order they show in the eve app (it doesn't edit how  homekit sees it). No way of checking the wind guage but it's on my christmas list ;-)

**Comment by ukstorm** [comment]
We had rain yesterday and all read outs seem fine! The only thing I haven't figured out is how to ask Siri :-)

**Comment by planetk** [comment]
Great that it works. Unfortunately there is no support in IOS9 for custom services.
