### ISSUE TITLE
Netatmo Welcome support?

### ISSUE THREAD

**Issue by Zyg0te** [planetk/homebridge-netatmo#13]
Hey!

While Homekit does not include support for cameras yet (as far as I know anyway), it might be able to detect motion and audio as that's been done with the Nest Cam already. Would be great to get this for Netatmo's camera as well.

**Comment by planetk** [comment]
Hi,

I'm about to implement welcome support. Since I do not own a welcome, I'm not sure what exactly would be in the API. I guess getHomeData will be the way to go.

So if anybody could provide the JSON response to getHomeData call. that would help a lot.

Kind regards
Stefan

**Comment by planetk** [comment]
very basic welcome support is included. To activate add folowing section to your config (inside netatmo section):

    "deviceTypes": [
        "weatherstation",
        "thermostat",
        "welcome"
    ]

**Comment by coliflower** [comment]
Do you mean so ?

>     		"platform": "netatmo",
			"deviceTypes":
			[
				"weatherstation",
				"thermostat",
				"welcome"
			],
			"name": "Netatmo",
			"ttl": 5,

**Comment by planetk** [comment]
right, that shoud work (after deleting persist and accessories folder and maybe deleting the existing device (or reseting homekit) on ios)

**Comment by marcodesantis71** [comment]
Hi Planetk

any news for welcome support?

I Have 2 welcomes but at the moment I see only one motion sensor
