### ISSUE TITLE
New Version throws errors

### ISSUE THREAD

**Issue by macjeff** [planetk/homebridge-netatmo#17]
I was working fine but updated the plugin this morning.  Now I get this.  Probably due to wind gauge I have.   Any suggestions.   For now I will pull the netatmo from my config.jsn until we figure this out.

ReferenceError: gustSensor is not defined
    at module.exports (/usr/local/lib/node_modules/homebridge-netatmo/services/weatherstation-wind-legacy.js:120:3)
    at new WeatherStationAccessory (/usr/local/lib/node_modules/homebridge-netatmo/devices/weatherstation.js:58:83)
    at .<anonymous> (/usr/local/lib/node_modules/homebridge-netatmo/devices/weatherstation.js:135:22)
    at .<anonymous> (/usr/local/lib/node_modules/homebridge-netatmo/devices/weatherstation.js:125:5)
    at .<anonymous> (/usr/local/lib/node_modules/homebridge-netatmo/node_modules/netatmo/netatmo.js:325:14)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-netatmo/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-netatmo/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)

**Comment by planetk** [comment]
Hi,

sorry. This was a very stupid typo, I did not find, since I do not own a wind sensor.
Should be fixed now. Thanks for your helpful advice!

**Comment by macjeff** [comment]
Your welcome but DONT buy the wind sensor just yet.  Literally we lost trees in our yard from a mini tornado and it said 4mph.   They had me move it to the top of the roof.  Same issues.  Then to 18 inches above the roof.  Same issues,   And each time I have to pay a guy to go on roof because I don't do heights.   Finally they said they found and issue and fixed in firmware but 75% of the ones out there have update issues.  So I have to ship mine back.  But they won't send one in advance so I have to pay someone to take it down and then pay someone to put it back up.   So I am going to wait a few months and buy one at amazon and return the old one!!!

This looks REALLY cool.  The company admits Netatmo changed the way people get weather data but they did not do everything right.

https://www.indiegogo.com/projects/weatherflow-smart-weather-stations#/

Ok I will stop rambling and test now.  Will reply soon.  Just trying to save people the frustration I went (going) through.

**Comment by macjeff** [comment]
Ok.  No errors this time but both the RAIN and WIND gauge show up but when you go into the data its all there but the columns say N/A

I can do two things to help.  One is send screenshots if you want.

The other is to figure out by the data what each column should say and I can send you the names.  

Let me know how I can help!!

Jeff

**Comment by planetk** [comment]
Hi,
thanx again for your valuable input. Sad to hear the story about your wind sensor. I had quite similar troubles whith byin a thermostat. Since it turned out it's not compatible with my heating, it now more or less a testing device. I like the indiegogo project but $ 200 is not that few ...

Pretty strange behaviour, because my rain sensor works like a charm. I'll try to implement some debug mode config switch, which might help me to find out more about the prob.

I suspect, it might be something about units and max/min values. Since I'm living in Europe I'm going with metric system instead of imperial.

So I'm measuring speed in km/h instead of mph. In rain in mm. That might be differences ...

If you do not mind, I'd like to ask you some more questions:

- You do have one rain and one wind sensor, right?
- Could you please login to http://dev.netatmo.com and the visit
following page:
https://dev.netatmo.com/dev/resources/technical/reference/weatherstation/getstationsdata
There is a try it block. And once you press the button you should find a repsonse.
If you could drill down the reponse tree and provide some data (leaving out secret keys and personal info) that would be biggest help possible,

Thank you so much for your help!

Kind regards
Stefan

**Comment by macjeff** [comment]
yes I have both 

body:
▼devices:
left out for security
▼modules:
▼
_id: "03:00:00:00:df:88"
type: "NAModule4"
last_message: 1469905078
last_seen: 1469905059
▼dashboard_data:
time_utc: 1469905059
Temperature: 23.1
temp_trend: "stable"
Humidity: 51
CO2: 747
date_max_temp: 1469867636
date_min_temp: 1469856513
min_temp: 22.9
max_temp: 23.9
▼data_type:
"Temperature"
"CO2"
"Humidity"
module_name: "Tucker/Ashton"
last_setup: 1405996751
battery_vp: 5614
battery_percent: 79
rf_status: 67
firmware: 44
▼
_id: "05:00:00:01:37:7a"
type: "NAModule3"
last_message: 1469905078
last_seen: 1469905078
▼dashboard_data:
time_utc: 1469905065
Rain: 0
sum_rain_24: 0.35572975140337
sum_rain_1: 0
▼data_type:
"Rain"
module_name: "Rain Gauge"
last_setup: 1433018675
battery_vp: 6050
battery_percent: 100
rf_status: 84
firmware: 8
▼
_id: "03:00:00:00:de:fa"
type: "NAModule4"
last_message: 1469905078
last_seen: 1469905059
▼dashboard_data:
time_utc: 1469905059
Temperature: 20.5
temp_trend: "stable"
Humidity: 65
CO2: 802
date_max_temp: 1469881509
date_min_temp: 1469852853
min_temp: 18.6
max_temp: 20.5
▼data_type:
"Temperature"
"CO2"
"Humidity"
module_name: "Basement"
last_setup: 1404262753
battery_vp: 5645
battery_percent: 80
rf_status: 84
firmware: 44
▼
_id: "03:00:00:00:e5:52"
type: "NAModule4"
last_message: 1469905078
last_seen: 1469905040
▼dashboard_data:
time_utc: 1469905040
Temperature: 23
temp_trend: "stable"
Humidity: 50
CO2: 581
date_max_temp: 1469886942
date_min_temp: 1469869464
min_temp: 22.5
max_temp: 23.2
▼data_type:
"Temperature"
"CO2"
"Humidity"
module_name: "Sunroom"
last_setup: 1406563550
battery_vp: 5757
battery_percent: 87
rf_status: 80
firmware: 44
▼
_id: "02:00:00:02:7d:88"
type: "NAModule1"
last_message: 1469905078
last_seen: 1469905065
▼dashboard_data:
time_utc: 1469905065
Temperature: 31.8
temp_trend: "up"
Humidity: 73
date_max_temp: 1469905065
date_min_temp: 1469866463
min_temp: 21.5
max_temp: 31.8
▼data_type:
"Temperature"
"Humidity"
module_name: "Outdoor"
last_setup: 1403928823
battery_vp: 5908
battery_percent: 96
rf_status: 87
firmware: 44
▼
_id: "06:00:00:00:dd:de"
type: "NAModule2"
last_message: 1469905078
last_seen: 1469905078
▼dashboard_data:
WindAngle: 188
WindStrength: 6
GustAngle: 143
GustStrength: 15
time_utc: 1469905065
▼WindHistoric:
▼
WindStrength: 6
WindAngle: 200
time_utc: 1469901739
▼
WindStrength: 6
WindAngle: 217
time_utc: 1469902040
▼
WindStrength: 6
WindAngle: 200
time_utc: 1469902342
▼
WindStrength: 4
WindAngle: 178
time_utc: 1469902643
▼
WindStrength: 7
WindAngle: 197
time_utc: 1469902944
▼
WindStrength: 9
WindAngle: 182
time_utc: 1469903245
▼
WindStrength: 10
WindAngle: 191
time_utc: 1469903546
▼
WindStrength: 8
WindAngle: 193
time_utc: 1469903848
▼
WindStrength: 6
WindAngle: 194
time_utc: 1469904155
▼
WindStrength: 7
WindAngle: 213
time_utc: 1469904457
▼
WindStrength: 6
WindAngle: 192
time_utc: 1469904764
▼
WindStrength: 6
WindAngle: 188
time_utc: 1469905065
date_max_wind_str: 1469903245
date_max_temp: 1469851393
date_min_temp: 1469881855
min_temp: -0.8
max_temp: 0
max_wind_angle: 225
max_wind_str: 22
▼data_type:
"Wind"
module_name: "Wind Gauge"
last_setup: 1464467149
battery_vp: 5940
battery_percent: 97
rf_status: 75
firmware: 17
►place:[object Object]
station_name: "MACWeather"
type: "NAMain"
▼dashboard_data:
AbsolutePressure: 997.8
time_utc: 1469905067
Noise: 52
Temperature: 27.4
temp_trend: "stable"
Humidity: 50
Pressure: 1015.5
pressure_trend: "stable"
CO2: 688
date_max_temp: 1469902344
date_min_temp: 1469853202
min_temp: 23.3
max_temp: 27.4
▼data_type:
"Temperature"
"CO2"
"Humidity"
"Noise"
"Pressure"
co2_calibrating: false
date_setup: 1403924772
last_setup: 1403924772
module_name: "Kitchen- Main"
firmware: 124
last_upgrade: 1439977271
wifi_status: 29
►user:[object Object]
status: "ok"
time_exec: 0.030011892318726
time_server: 1469905556

**Comment by planetk** [comment]
Cool! Thank you very much!

Id did add some fixes to the rain sensor, so when there is no rain, ther should not occur communication errors any longer. I'll have a look what I can do about the wind sensor.

**Comment by planetk** [comment]
Hi Jeff,

I was able to implement some fake calls based on the data you provided. Now your Wind sensor should show data. (I guess your using beaufort values for strength, is it?

Thanx a lot for your help.

I'm closing this, since I'm confident it works now. Feel free to reopen or add a new issue, if you experience any trouble.
