### ISSUE TITLE
Weather-Station not visible in EVE App ...

### ISSUE THREAD

**Issue by coliflower** [planetk/homebridge-netatmo#19]
I installed the homebridge on my MacBook … should works fine - I see the homebridge in EVE but I do not see the plug-in :-(

The plugin was installed with: `sudo npm install -g homebridge-netatmo`
It is installed together with the homebridge itself + the plugin „homebridge-knx“ under: `/usr/local/lib/node_modules/`

The config.json:
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:40",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is a configuration file.",
    "accessories": [
        {
            "accessory": "WeMo",
            "name": "Coffee Maker"
        }
    ],
    "platforms": [
    	{
    	"platform": "netatmo",
    	"name": "NETATMO",
		"ttl": 5,    		
		"auth": {
    		"client_id": „579 … 8df",
    		"client_secret": „E ... Szav",
    		"username": „email",
			"password": „password"
			}
    	},
        {
            "platform" : "KNX",
            "name": "KNX",
            "knxd_ip": "10.0.100.8",
            "knxd_port": 6720,
            "knxd_do_not_read_set_groups": true,
            "accessories": [
                {
                    "name": "WK eldoLED",
                    "services": [
                        {
                            "type": "Lightbulb",
                            "description": "Beleuchtung in der Kuchl",
                            "name": "WK eldoLED",
                            "On": {
                                "Set": "5/1/0",
                                "Listen": ["5/1/4"]
                            },
                            "Brightness": {
                                "Set": "5/1/3",
                                "Listen": ["5/1/5"]
                            }
                        }
                    ]
                }
            ]
        }
    ]
}

**Comment by planetk** [comment]
Hi,

your config looks ok. Are you sure you use the very latest version? The plugin is undergoing major changes at the moment. So there have been some non functional versions.

If you have the latest version (available since yesterday in the evening), could you please send some info from the homebridge log,in case there is an error?

And, i know it' anoying, but stopping homebridge, deleting the accessories and persist folder as well as closing the eve app an resetting homekit setting on the iphone, sometime help.

If all this does not help, you might also please send me some json output from yout netatmos "getstationsdata" call. (I suppose you try to connect to a weatherstation, right?

Kind regards
Stefan

**Comment by planetk** [comment]
BTW: I guess using " " versus „“ in your config is just an issue with your editor and you are using plain double quotes ("), right?

**Comment by coliflower** [comment]
Hi Stefan,

thanks a lot for your quick feedback :-)

the version see the output after the install of the plagin: 
`MBP:~ dariusz$ sudo npm install -g homebridge-netatmo
/usr/local/lib
└─┬ homebridge-netatmo@0.1.0 
  └── netatmo@1.5.0  (git+https://github.com/karbassi/netatmo.git#461c48c97e0377e79f6e73f6f72ac4dd8675ac7d)`

If not, how to update, please ?

I already sopped homebridge and deleted the mentioned files … and all the things your mentioned above.

May I also ask to you what the path to the logs is, please :-) ?

Thanks !
Dariusz

**Comment by coliflower** [comment]
> BTW: I guess using " " versus „“ in your config is just an issue with your editor and you are using plain double quotes ("), right?

YES, I use TextWrangler with config of JSON, UTF-8 and (UNIX-LF)

BTW: are ' ' also OK or only " " ?

**Comment by planetk** [comment]
yes, if syntax would be a problem, homebridge would complain anyhow.
To be sure you could validate the file content at:
http://jsonlint.com/

Your software version looks ok.for the logfile you might check the output on your console when starting homebridge.

Some sources say its at "/var/log/homebridge.log". But the output on the screen after starting with "homebridge" command would be fine for me to find problems.

**Comment by coliflower** [comment]
`/var/log/` has a lot of .log but no homebridge.log inside :-(

Here that is the output after starting homebridge itself:

MBP:~ dariusz$ homebridge
[2016-08-01 18:52:50] Loaded plugin: homebridge-knx
[2016-08-01 18:52:50] Registering platform 'homebridge-knx.KNX'
[2016-08-01 18:52:50] ---
[2016-08-01 18:52:52] Loaded plugin: homebridge-netatmo
[2016-08-01 18:52:52] Registering platform 'homebridge-netatmo.netatmo'
[2016-08-01 18:52:52] ---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[2016-08-01 18:52:52] Homebridge is running on port 51826.

**Comment by planetk** [comment]
Well, that does not look ok.
You should see some entries like:
[Mon Aug 01 2016 19:55:39 GMT+0200 (CEST)] Loading 1 platforms...
[Mon Aug 01 2016 19:55:39 GMT+0200 (CEST)] [netatmo weather] Initializing netatmo platform...
[Mon Aug 01 2016 19:55:39 GMT+0200 (CEST)] Loading 0 accessories...
[Mon Aug 01 2016 19:55:40 GMT+0200 (CEST)] [netatmo weather] refreshing weatherstation device ff:ee:aa:02:00:01 (Inside Module)
[Mon Aug 01 2016 19:55:40 GMT+0200 (CEST)] [netatmo weather] refreshing weatherstation module 11:22:33:44:55:66 (Outside Module)
[Mon Aug 01 2016 19:55:40 GMT+0200 (CEST)] [netatmo weather] refreshing weatherstation module 02:03:04:05:06:01 (Rain)

**Comment by planetk** [comment]
If you don't mind reseting your hombridge settings on iPhone once more (and deleting the accessories and persist folder) you might to add try following line to your config:

           "ttl": 5,
            **"mockapi": "wind",**
            "auth": {

After that you should see some dummy devices with dummy data in Eve. This would indicate a problem with your netatmo stuff. otherwise there seems to something wrong with your homebridge installation.

**Comment by planetk** [comment]
Could you pleas also temporarily disable the knx plugin?

**Comment by coliflower** [comment]
Hmmm,

I added the mockapi …
I reseted the iPhone HomeKit ...
I deleted both folders …
I deinstalled the homebridge-knx plugin …
I put only Netatomo infos into the config.json …

I only see the homebridge in EVE :-(((((((

**Comment by planetk** [comment]
Sorry to hear that... And thank you for your patience.

But you did see data from the knx device?
I think it is really a problem with your installation. You should see some more output from netatmo plugin.

I did quite same install (not with sudo) but that should not be the problem..

My versions are:
$ npm -version
2.10.1
$ node --version
v0.12.4

Do you have access to a different computer?

**Comment by coliflower** [comment]
I installed node + npm via a package from the homebridge site for OS X …

MBP:~ dariusz$ npm -v
3.10.5
MBP:~ dariusz$ node -v
v4.4.7
MBP:~ dariusz$

Node must be >= 4.0.0 according to homebridge-knx.

KNX-plugin was not ready, yet … Therefore I have no idea whether YES/NO ..

But I have an iTunes plugin running …

MBP:~ dariusz$ homebridge
[2016-08-01 20:39:53] Loaded plugin: homebridge-itunes
[2016-08-01 20:39:53] Registering platform 'homebridge-itunes.iTunes'
[2016-08-01 20:39:53] ---
[2016-08-01 20:39:53] Loaded plugin: homebridge-netatmo
[2016-08-01 20:39:53] Registering platform 'homebridge-netatmo.netatmo'
[2016-08-01 20:39:53] ---
Load homebridge-itunes.iTunes
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[2016-08-01 20:39:53] Homebridge is running on port 51826.

**Comment by planetk** [comment]
I'll try to setup similar environment. It will take me a while, since I'm a little busy.

**Comment by planetk** [comment]
Ok, I tried defferent newer versions with nvm. All work fine.

May it is a rights issue.
Possibly you should try to install modules without sudo or run homebridge with sudo as well.

**Comment by coliflower** [comment]
I started homebridge with sudo, unfortunately the same result, only iTunes below homebridge is visible.

Thanks a lot so far !!

**Comment by planetk** [comment]
One more question:
are you using ios10 beta?
because homerbridge is known to to have trouble with this new version. especially when working with platforms instead of accessories:
https://github.com/nfarina/homebridge/issues/662

**Comment by planetk** [comment]
Finally it loks like your config.json is not parsed.
You could try to change the PIN in order to verify this.
https://github.com/nfarina/homebridge/issues/564

**Comment by coliflower** [comment]
> One more question:
are you using ios10 beta?

No, I use 9.3.2

**Comment by coliflower** [comment]
Hi Stefan !

I think it works - but - what I do not understand ist (maybe that ist different OS X to „Linux“ installation ?

Usually the JSON should be in:
`/usr/local/lib/node_modules/homebridge/config.json`
It works also fine with iTunes plugin …

Now I moved the JSON into:
`~/.homebridge/config.json`
It seems to work with iTunes + Netatmo …

> MBP:~ dariusz$ homebridge
[2016-08-02 08:24:45] Loaded plugin: homebridge-itunes
[2016-08-02 08:24:45] Registering platform 'homebridge-itunes.iTunes'
[2016-08-02 08:24:45] ---
[2016-08-02 08:24:47] Loaded plugin: homebridge-netatmo
[2016-08-02 08:24:47] Registering platform 'homebridge-netatmo.netatmo'
[2016-08-02 08:24:47] ---
[2016-08-02 08:24:47] Loaded config.json with 0 accessories and 2 platforms.
[2016-08-02 08:24:47] ---
[2016-08-02 08:24:47] Loading 2 platforms...
[2016-08-02 08:24:47] [NETATMO] Initializing netatmo platform...
[2016-08-02 08:24:47] [NETATMO] CAUTION! USING FAKE NETATMO API: wind
[2016-08-02 08:24:47] [NETATMO] refreshing weatherstation device 10:00:00:00:00:01 (MyStation Livingroom)
[2016-08-02 08:24:47] [NETATMO] refreshing weatherstation module 10:00:00:00:00:02 (MyStation Outdoor)
[2016-08-02 08:24:47] [NETATMO] refreshing weatherstation module 10:00:00:00:00:05 (MyStation Wind Gauge)
[2016-08-02 08:24:47] [NETATMO] refreshing weatherstation module 10:00:00:00:00:03 (MyStation Rainmeter)
[2016-08-02 08:24:47] [NETATMO] WARN - Netatmo: Error: No fake api call for 'getthermostatsdata-wind'! using default
[2016-08-02 08:24:47] [NETATMO] refreshing thermostat device 20:00:00:00:00:01 (Station)
[2016-08-02 08:24:47] [NETATMO] Initializing platform accessory 'MyStation Livingroom'...
[2016-08-02 08:24:47] [NETATMO] Initializing platform accessory 'MyStation Outdoor'...
[2016-08-02 08:24:47] [NETATMO] Initializing platform accessory 'MyStation Wind Gauge'...
[2016-08-02 08:24:47] [NETATMO] Initializing platform accessory 'MyStation Rainmeter'...
[2016-08-02 08:24:47] [NETATMO] Initializing platform accessory 'Station'...
[2016-08-02 08:24:47] Initializing iTunes platform...
[2016-08-02 08:24:47] Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
> [2016-08-02 08:24:47] Homebridge is running on port 51826.

**Comment by planetk** [comment]
I think the hombridge developer changed the Location to home.
iTunes does not need infos from config to create accessoires.
Anyhow, good to hear it works.
