### ISSUE TITLE
Don't show shared Netatmo stations

### ISSUE THREAD

**Issue by patricks** [planetk/homebridge-netatmo#22]
I have many shared Netatmo stations, it would be nice if there would be an options to hide this stations.

**Comment by planetk** [comment]
Hi,

this is one of the topics on the agenda. Unfortunately I don't have that much spare time to develop this as fast as I want. I will do my best to implement this soon.

Thanx for you input!

Kind regards
Stefan

**Comment by patricks** [comment]
I habe create a pull request #23 where I can filter via the device it. This feature is implemented in the latest netatmo npm.

**Comment by planetk** [comment]
I'll close this for now. (Thanx again for the pull request).

Maybe I'll reopen this to enhance service selection.
