### ISSUE TITLE
HomeKit App tells me "not supported" for all Netatmo devices since update...

### ISSUE THREAD

**Issue by Crady123** [planetk/homebridge-netatmo#24]
Hi there,

Since updating the netatmo plugin for home bridge on my Raspberry Pi my HomeKit App (iOS 10 beta) tells me, that the Netatmo devices are not supported...

Then I updated Node.js from v4.0.0 to v4.4.7 - but no luck.

When trying to reinstall the Netatmo Plugin I am getting this messages:

pi@raspberrypi:~ $ sudo npm install -g homebridge-netatmo
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-installed/node_modules/readdir-scoped-modules requires graceful-fs@'^4.1.2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-installed/node_modules/graceful-fs,
npm WARN unmet dependency which is version 3.0.8
homebridge-netatmo@0.1.1 /usr/local/lib/node_modules/homebridge-netatmo
├── glob@7.0.5 (path-is-absolute@1.0.0, fs.realpath@1.0.0, inherits@2.0.1, inflight@1.0.5, once@1.3.3, minimatch@3.0.2)
├── node-cache@3.0.0 (clone@1.0.2, lodash@3.10.1)
├── netatmo@1.5.0 (moment@2.14.1, request@2.74.0)
└── async@2.0.1 (lodash@4.14.2)

What to do?

Thanks!

Crady

**Comment by planetk** [comment]
Hi,

thanx for your input. I will try to get an iOS 10 beta device within the next days. iOS 10 is known to cause trouble with custom characteristics not officially supported by apple (see: nfarina/homebridge#662)

I will try to find out more as soon as I got the device.

**Comment by Crady123** [comment]
Hmm ok for iOS10... but what about the messages showing up during install?

Nodes.js is 4.4.7
Graceful-fs is 4.1.5

So I don´t know why I receive that messages...

**Comment by deadbone** [comment]
Same issue for me (netatmo weather station with ios 10 (or 9) as reported on slack (#random).
Let me know if I can provide some help to test some workaround (homebridge in docker on a NAS synology)

**Comment by planetk** [comment]
Hi,
It seems that no cervices were added when running as a demon process. service look up was fixed in the newest version.

**Comment by planetk** [comment]
@Crady123 Not sure about the messages but when googling for it looks like you npm versioning is messed up.

**Comment by deadbone** [comment]
Thanks for the fix. It's working like a charm :-)
