### ISSUE TITLE
Sensors as Event Triggers

### ISSUE THREAD

**Issue by torange** [planetk/homebridge-netatmo#27]
In its current state, the netatmo plugin does not appear to support device characteristics as event triggers. The plugin does not push sensor changes in a live manner to the homebridge server, so event triggers do not function unless a homekit app is opened, which causes the device characteristics to be called/updated.

Example: I want to have a light turn on if my CO2 levels rise above 1000 ppm.  I can configure an event to appear as follows: If Netatmo CO2 level reaches 1,000 ppm, then change the power state of my Hue bulb to On.  

However, once my CO2 levels reach 1,000 ppm, nothing happens.  When I open up a HomeKit app, such as the iOS 10 Home app, the device value is updated, and suddenly, the event is triggered.  

Here is discussion on the issue in another plugin that may be of some help in implementing this feature for the netatmo plugin:
https://github.com/rthewhite/homebridge-homewizard/issues/5

Thanks!

**Comment by planetk** [comment]
Hi,
thanks for your input. This goes to the top of my priority list. But unfortunately I'm very busy quite now ... :(

**Comment by wh33ler** [comment]
any news on this? without any pulling service you can't build any decent triggers

**Comment by halonsokey** [comment]
Any News of this Feature? i am really interested on this
Thank you
How can i Help You?

**Comment by planetk** [comment]
Hi,
there is a dev branch which I'm currently testing, which supports this. But according to netatmo I'm causing to much traffic, altough I'm in the limits given.

Please checkout this:
https://github.com/planetk/homebridge-netatmo/tree/dev

**Comment by halonsokey** [comment]
Can you Help me how to install it? i am very new in this things but i am really interested on you job?
i had this error
1/25/2017, 4:01:43 PM] ====================
[1/25/2017, 4:01:43 PM] ERROR LOADING PLUGIN homebridge-netatmo:
[1/25/2017, 4:01:43 PM] Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-netatmo/index.js:4:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
[1/25/2017, 4:01:43 PM] ====================

**Comment by torange** [comment]
Seems to be working thus far on the dev branch. Nice to see the wind/rain gauge implementation as well, though I am getting errors from the rain gauge. 

Thanks for your work!

halonsokey, a dependency is missing (async) so you should make sure your homebridge, npm, and node installations are setup correctly.

**Comment by savealive** [comment]
@torange is really working for you? I'm also on the dev branch but not getting any notifications unless I open the Home app.

**Comment by torange** [comment]
@savealive I'm not entirely sure.  it seemed like a trigger did fire, but I didn't receive a notification about it.  I'll do a little more of a stress test later today

**Comment by adekka** [comment]
https://github.com/snOOrz/homebridge-aqara/issues/25

I have the same issue but with a different plugin. Wondering how I can help to sort out what is causing this.

**Comment by torange** [comment]
@savealive you're right, it still doesn't work unfortunately.  Someone else in my home must have opened their home app, causing the event trigger.

**Comment by planetk** [comment]
seems there's not much i can do about it: Check https://github.com/nfarina/homebridge/issues/1006
