### ISSUE TITLE
Retry on "No Response API error"

### ISSUE THREAD

**Issue by glumb** [planetk/homebridge-netatmo#28]
After I restart my Raspberry Pi, sometimes this error occurs in the Homebridge logs `[9/17/2016, 4:17:39 PM] [Netatmo weather] ERROR - Netatmo: Error: Authenticate error: No response`.
I don't know what causes this error.
Homebridge does not work until I restart the service manually.

There should be some sort of retry mechanism. I could of course observe the logs and restart the service in the event of this specific log line, but wouldn't it be better, if the service (homebridge-netatmo) tries to reconnect itself? Or do you see this functionality in netatmo.js?

**Comment by planetk** [comment]
Sorry, been off a while. This is definitly a good point. Although I'm not sure if it should be put into the netatmo.js. I have never heard of this kind of issues. If several people experience this behaviour, I guess the netatmo.js should fix this.

I'll try to look at this soon.

**Comment by planetk** [comment]
Hi,

i just updated to the latest netatmo api in the dev branch

https://github.com/planetk/homebridge-netatmo/tree/dev

This might fix it.
