### ISSUE TITLE
Air quality 

### ISSUE THREAD

**Issue by dawiinci** [planetk/homebridge-netatmo#3]
I have some air quality sensors listed in the Eve App but if I ask Siri to tell me the air quality she says there are no air quality sensors.

**Comment by planetk** [comment]
As far as I know, siri does not support all characteristics. Air quality is unfortunately not one of them. I'm sorry to say, but there's nothing I can do about this. We have to wait for Apple to add this support to iOS in future revisions.

Please check this article as well:
http://9to5mac.com/2015/12/21/smart-home-combo-review-homekit-elgato-eve-temperature-air-quality-sensor-mood-light/
