### ISSUE TITLE
Weatherstation battery level 

### ISSUE THREAD

**Issue by mrjoda66** [planetk/homebridge-netatmo#30]
Hello, first, sorry for my english...

I'm using homekit and I would like to know is there is a way to add the exterior wheatherstation battery level as accessory in homekit?

I see all the measurement of temperature, humidity, etc.. but not the battery level.

Merci

**Comment by planetk** [comment]
Hi,

battery level should be there. Are you using elgato eve? This sometimes hides some values. you should be able to edit your device list and add the battery level

**Comment by mrjoda66** [comment]
No, I'm only using iOS home application to read values of the netatmo wheather station and control a Lifx bulb.

All work correctly, I've all values in the iOS app except the battery level.

**Comment by planetk** [comment]
ios home does not display the value. You might see it with elgato eve.
