### ISSUE TITLE
[Request] Enable/Disable multiple Netatmo

### ISSUE THREAD

**Issue by mbnn** [planetk/homebridge-netatmo#31]
Hello,

Thank you for your amazing plugin for homebridge :)
The only problem I have with the plugin right now is that it shows all Netatmo weatherstations in Homebridge/kit, so also those of our friends. Is it possible in some way to restrict only showing your own weatherstation or something?

Thank you :)

**Comment by planetk** [comment]
Hi, 

Thanks for your input.

there is an undocumented feature which allows you to select specific devices:

check this:
https://github.com/planetk/homebridge-netatmo/pull/23

The trick is to add the "options_weather" section in your config:

"options_weather": {
  "device_id": "XX:XX:XX:XX:XX:XX"
},

**Comment by mbnn** [comment]
Ok cool, so how can i find out what my device id is? :)

**Comment by planetk** [comment]
Hmm, if I remember right, it should be the mac address of your Main (Inside) Module.

**Comment by planetk** [comment]
Maybe there's a sticker somewher on the box: the id is like '11:a1:22:bb:34:fe'

**Comment by mbnn** [comment]
Yep, found it, thank you :) It's the main mac address indeed!
