### ISSUE TITLE
Background polling for better response times 

### ISSUE THREAD

**Issue by skrollme** [planetk/homebridge-netatmo#33]
First of all thanks for this great plugin so far. It was a plug&play solution for me, as a non-nodeJS dev ;)
But back to topic:
This "issue" is more a feature-suggestion/idea than an issue.
I'm often facing the problem, that the Home.app does not display my Netatmo's data but when I simultaneously look into the homebridge log, I see the netatmo fetching logs succeeding.
Another fetch 1-2 minutes later (within the configured TTL) succeeds instantly.

So I came up with the idea of switching to an continuously running background fetch for netatmo's data to answer the Homekit request faster.

Have you thought about it before? Any possible disadvantages? Maybe Netatmo-API-Limitations?

**Comment by mrose17** [comment]
@skrollme - the question always comes down to: how often should you poll? the hard part is knowing you are polling for a new user interaction after X amount of inactivity, or are you polling for a continuing user interaction. when you know the polling interval, you can then cache as appropriate.

in this case, suppose you were to poll every 10 minutes until a request came into the accessory, and then after that, to poll every 10 seconds until no request had been seen for 10 minutes. would that work well? i'm not sure... what do you think?

**Comment by skrollme** [comment]
I thought of a continuous poll (every 10 minutes or so). Especially for - normally - slow changing weather data that would be fine. So maybe no real change in frequency, even if someone fetches the data via homekit.

**Comment by mrose17** [comment]
so, probably the answer here is to see what caching, if any, occurs... i hope to take a look this weekend at the plugin to see what's going on with that.

**Comment by davidbb** [comment]
FYI, from netatmo's API docs, https://dev.netatmo.com/dev/resources/technical/guides/ratelimits

Polling for weatherstation data should not be done more frequently than once every 10 minutes. Thermostat data should not exceed once every hour.

**Comment by planetk** [comment]
Done in current dev branch, which is under test:
https://github.com/planetk/homebridge-netatmo/tree/dev
Cheers
Stefan
