### ISSUE TITLE
netatmo dependency updated

### ISSUE THREAD

**Issue by karbassi** [planetk/homebridge-netatmo#35]
Hello,

I've updated the [netatmo package to v2.0.0](https://github.com/karbassi/netatmo/releases/tag/v2.0.0). This is a friendly reminder for you if you want to update your [package.json](../blob/master/package.json#L16).

Cheers,

Ali

**Comment by planetk** [comment]
Thanx for the hint.

I'm using the latest api in the dev branch I'm currently testing.

Kind regards
Stefan
