### ISSUE TITLE
Support for Netatmo Presence

### ISSUE THREAD

**Issue by nicktmro** [planetk/homebridge-netatmo#37]
Hi,

Can you please confirm if you plan to add support for Netatmo Presence? I own one, so I'd be glad to help you test :)

Cheers,
Nick

**Comment by adekka** [comment]
Yes, let us know! +1

**Comment by nicktmro** [comment]
@planetk the good news is that I got a sample app going and I am getting back homedata API responses. The better news is that Welcome and Presence seem to be using the same API.

I have the API response in BBEdit and I'm going to sanitise it (remove duplicate events, etc). What is the best way to send it to you?

**Comment by planetk** [comment]
Hi,
@nicktmro  thanks for your comment and your effort!

I have done some major progress on refactoring and event notification. So next is welcome and presence.

If you could provide the response, this would be great. Also if anybody else owning a welcome or presence could provide the (anonymized) response of a "gethomedata" call, that would be great.

You could post it as a comment here, or use slack (homebridgeteam.slack.com) and send me a direct message (@planetk)

Thanx for your support!

**Comment by nicktmro** [comment]
Sure thing. I'll slack you shortly with a pretty comprehensive (sanitised) API response for my Presence camera.

**Comment by planetk** [comment]
at least simple motion sensor should work for now.
