### ISSUE TITLE
Login id / secret

### ISSUE THREAD

**Issue by kohlsalem** [planetk/homebridge-netatmo#4]
Hi, 

in the Readme it is is written:

    "client_id": "XXXXX Create at https://dev.netatmo.com/",
    "client_secret": "XXXXX Create at https://dev.netatmo.com/",

Can you please elaborate in the Readme a little more, where i can find the respective entries on https://dev.netatmo.com/ ?

At least for me it is not obvious....

Thanks
Michael

**Comment by planetk** [comment]
Hi, thanks for pointing this out.

I did an update to the readme. Please find following steps there:

1. Register at http://dev.netatmo.com as a developer
2. After successful registration create your own app by using the menu entry "CREATE AN APP"
3. On the following page, enter a name for your app. Any name can be chosen. All other fields of the form (like callback url, etc.) can be left blank.
4. After successfully submitting the form the overview page of your app should show client id and secret.

I hope, this makes it clearer.

Kind regards
Stefan
