### ISSUE TITLE
[netatmo-platform] ERROR - Netatmo: Error: Authenticate error: invalid_grant

### ISSUE THREAD

**Issue by Knobiwahn** [planetk/homebridge-netatmo#40]
the part of my config....

"platforms": [
        {
            "platform": "netatmo",
            "name": "netatmo-platform",
            "ttl": 5,
            "deviceTypes":[
              "weatherstation"],
            "auth": {
    	        "client_id": "588*****************32",
                "client_secret": "Y5*************BhL",
                "username": "no***********mx.ch",
                "password": "***********"
            }
        }
    ]
}

got no idea what i did wrong?

**Comment by planetk** [comment]
Hi,

your clientID looks pretty short.

Check the info on your personal account page at netatmo:

https://dev.netatmo.com/dev/myaccount

Check the data for your app in the technical parameters section.

**Comment by Knobiwahn** [comment]
Hi,

Thanks for your help. i didnt post everything. So for sure i createt 2 apps an did copy paste withe my client id but i still got that error.
So what you see is a part of my id

**Comment by preacha** [comment]
I got the same error anytime. What was the solution here?
