### ISSUE TITLE
Doesn't show the noise level accessory

### ISSUE THREAD

**Issue by schurig** [planetk/homebridge-netatmo#43]
I have a netatmo weather station running and there is no noise level accessory in the home app. These accessories were added to Home:

**Inside module**
* Temperature
* Humidity
* Carbon Dioxide
* Air Quality

**Outside module**
* Temperature
* Humidity

**Comment by planetk** [comment]
Hi,

thanx for your feedback. The home app unfortunately does not support noise characteristics, since it is no official homekit characteristics. You might want to use the elgato eve app.

Kind regards
Stefan
