### ISSUE TITLE
Historydata with EVE custom characteristics [Enhancement]

### ISSUE THREAD

**Issue by skrollme** [planetk/homebridge-netatmo#56]
I saw you already mentioned this in the homebridge-netatmo roadmap and wanted to ask, if your are still interested in this topic. I have not much experience in nodeJS (just started after discovering homebridge) but I would like to offer support. 
Do you already started with this topic or started investigating (GUIDs of EVE's custom characteristics)? I just found this https://gist.github.com/gomfunkel/b1a046d729757120907c (you already commented there as well) but he does not collected some GUIDs for the weatherdata-history so far.

**Comment by planetk** [comment]
Hi,
I did a couple of experiments and got some basic infos about how to display this data.
Unfortunately at the Moment I do not really have the time to proceed on this project.
Sorry for that. So if anybody likes to take care of this in the future, feel free to contact me and I'll provide the Info I already got ...

**Comment by skrollme** [comment]
Like I said, I'm not a nodeJS pro (more like a newbee), but I'm willing to look into it. If you could provide the infos you have (docs, custom-characteristics, debugging/testing-tools, already started branches?) that would be cool. Maybe here, or in a wiki-page in this repo.

**Comment by Krocko** [comment]
Hello. Any news about this?

**Comment by skrollme** [comment]
@Krocko you can take a look at this GIST https://gist.github.com/simont77/3f4d4330fa55b83f8ca96388d9004e7d if you are interested in participating in research and development of a working prototype of an eve-faking-accessory. Until now there are no news concerning a working-out-of-the-box-plugin, sorry.

**Comment by simont77** [comment]
Hi all,
just an update on that @skrollme said: now I've definitely understood Eve history protocol, at least enough to create a fake accessory whose history will show up in Eve.app. Unfortunately I'm not very good with nodejs, so translating it in a full featured history plugin for homebridge would take some time. Are you more skilled then me? I think that maybe the best way to proceed is to develop a library that can be included in any plugin. You will find all my latest findings in my gist, let me know if you need some clarification.
