### ISSUE TITLE
Weather station blocked

### ISSUE THREAD

**Issue by JotWee** [planetk/homebridge-netatmo#58]
I had to re-setup my pi and installed homebridge exactly as it was before, exact same config.json. 
But now the room module of the weatherstation is shown as “blocked”. Everything else works as it did before.
Any ideas, what I could do?

**Comment by skrollme** [comment]
Maybe you restarted Homebridge too often, so there were too many request to the netatmo-API and they temporarily blocked you.

**Comment by JotWee** [comment]
no, the exterior module works and I didn’t do more calls than usual

**Comment by skrollme** [comment]
Have you tried to fetch the _stationdata_ manually to check, if everything is ok at this point?
You can do test-calls here: https://dev.netatmo.com/resources/technical/reference/weatherstation/getstationsdata

**Comment by JotWee** [comment]
Yes, that looks perfectly fine
Usually Homekit blocks a device if a characteristic doesn’t conform to standards (whatever standards that are). I am using iOS 11 beta on all devices. But anyway, the problem only occurred after re-setup my Pi.

**Comment by JotWee** [comment]
with latest update of homebridge, things again work with iOS 11
