### ISSUE TITLE
 [netatmo platform] ERROR - Netatmo: Error: Authenticate error: invalid_client

### ISSUE THREAD

**Issue by bombadiltom** [planetk/homebridge-netatmo#63]
I keep getting this error, double checked client id and secret, created a new app, resetted an app...
Have there been any changes on Netatmo side?

**Comment by mikeBOLD** [comment]
Hi, have you checked your app status under https://dev.netatmo.com/myaccount/ ? I get the same error when I deactivate my app. Click on activate and see if it changes anything for you.

**Comment by bombadiltom** [comment]
Works again, did not change anything...
