### ISSUE TITLE
v0.2.1 not on https://www.npmjs.com/package/homebridge-netatmo?

### ISSUE THREAD

**Issue by seisfeld** [planetk/homebridge-netatmo#64]
Hi,

when installing the plugin via `npm install -g homebridge-netatmo` I seem to get v0.2.0 although the [README.md](https://github.com/planetk/homebridge-netatmo/blob/master/README.md) mentions v0.2.1 is out. How can I install/update to that version?

thanks
Stephan

**Comment by nxtpl** [comment]
Yeah how to install the dev version?
