### ISSUE TITLE
No netatmo thermostat detected

### ISSUE THREAD

**Issue by TheBluProject** [planetk/homebridge-netatmo#7]
Hi,

After the dick-move from netatmo of introducing the new model of netatmo thermostat that is directly homekit compatibile, I have been left with the older device that is not compatibile. I've been quite excited to see that you have added (partial) netatmo thermostat to your plugin, however my log does not show anything related to netatmo thermostat, it just detects adn registers all modules for netatmo weather station. Any ideas ?

**Comment by planetk** [comment]
Hi,
sorry for getting back to you a little late. I guess the problem is, that for a couple of releases I'm not using the deprecated generic API, but it uses a specific one for the weather station.

But asfaik the thermostat should have build in homekit support witou a need for homebridge usage ...
