### ISSUE TITLE
Standardize the weather station UUID's?

### ISSUE THREAD

**Issue by kcharwood** [planetk/homebridge-netatmo#8]
I built a [weather station](https://github.com/kcharwood/homebridge-weather-station) plugin for homebridge. I see there are some characteristics you have defined here as well.

Perhaps we should shoot to standardize those values?

**Comment by planetk** [comment]
Sounds like a great idea. Maybe we could have a separate repo including a JS lib, which defines a couple of Characteristics and Services?

In addition it might be worth to have a look at following page: https://gist.github.com/gomfunkel/b1a046d729757120907c
It's a list of characteristics used by elgato eve stations. So the popular Elgato Eve Homekit Client can have special ui widgets for those characteristics.

Unfortunately I found those to late, and I'm still wondering about how to integrate those without breaking with my current UIDs. Probably I will introduce some kind of configurable "eve mode"...

**Comment by planetk** [comment]
Services and characteristics are pluggable now. If we get a standard I'm ready to adopt ;-)

**Comment by Maxrus21** [comment]
environmental Sensing
temperature Characteristic
humidity Characteristic
pressure Characteristic
